name: code_review
on: push
  # Trigger the workflow on push
  # but only for the master branch
  #  push:
  #    branches:
  #      - master
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch-suffix: short-commit-hash
          reviewers: stefanbucur, asraa, tengpengli

